name: Deploy to VM

on:
  push:
    branches: [ "main" ]   # Falls dein Hauptbranch anders heißt, hier anpassen

jobs:
  deploy:
    runs-on: self-hosted
    steps:
      - uses: actions/checkout@v4

      - name: Deploy files
        run: |
          mkdir -p ~/ci-cd-deploy
          rsync -av --delete \
            --exclude ".git" \
            --exclude ".github" \
            ./ ~/ci-cd-deploy/