name: CI-CD Static Site Pipeline

on:
  push:
    branches: [ "main" ]

jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4

      - name: Setup SSH
        run: |
          mkdir -p ~/.ssh
          echo "${{ secrets.SSH_PRIVATE_KEY }}" > ~/.ssh/id_rsa
          chmod 600 ~/.ssh/id_rsa
          ssh-keyscan -p "${{ secrets.SSH_PORT || 22 }}" "${{ secrets.SSH_HOST }}" >> ~/.ssh/known_hosts

      - name: Upload static files
        run: |
          RELEASE_DIR="/home/azubi/deploy/releases/${{ github.sha }}"
          ssh -p "${{ secrets.SSH_PORT || 22 }}" "${{ secrets.SSH_USER }}@${{ secrets.SSH_HOST }}" "mkdir -p $RELEASE_DIR"
          rsync -avz -e "ssh -p ${{ secrets.SSH_PORT || 22 }}" \
            --exclude ".git" \
            ./ "${{ secrets.SSH_USER }}@${{ secrets.SSH_HOST }}:$RELEASE_DIR/"

      - name: Symlink switch
        run: |
          HOST="${{ secrets.SSH_HOST }}"
          USER="${{ secrets.SSH_USER }}"
          PORT="${{ secrets.SSH_PORT || 22 }}"
          RELEASE_DIR="/home/azubi/deploy/releases/${{ github.sha }}"
          CURRENT="/home/azubi/deploy/current"

          ssh -p "$PORT" "$USER@$HOST" bash -lc "
            set -e
            ln -sfn \"$RELEASE_DIR\" \"$CURRENT\"
          "

      - name: Cleanup old releases
        run: |
          ssh -p "${{ secrets.SSH_PORT || 22 }}" "${{ secrets.SSH_USER }}@${{ secrets.SSH_HOST }}" '
            cd /home/azubi/deploy/releases &&
            ls -1t | tail -n +6 | xargs -r rm -rf
          '