name: Deploy to VM

on:
  push:
    branches: [ "main" ]   # Falls dein Hauptbranch anders heißt, hier anpassen

jobs:
  deploy:
    runs-on: self-hosted
    steps:
      - uses: actions/checkout@v4

      - name: Deploy files
        run: |
          sudo mkdir -p ~/ci-cd-deploy
          sudo rsync -av --delete \
            --exclude ".git" \
            --exclude ".github" \
            ./ /var/www/html/